### ISSUE TITLE
Unable to instantiate receiver com.medavox.library.mutime.Persistence

### ISSUE THREAD

**Issue by williamsim** [medavox/MuTime#2]
java.lang.RuntimeException: Unable to instantiate receiver com.medavox.library.mutime.Persistence: java.lang.IllegalAccessException: access to class not allowed	
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2400)	
at android.app.ActivityThread.access$1700(ActivityThread.java:135)	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)	
at android.os.Handler.dispatchMessage(Handler.java:102)	
at android.os.Looper.loop(Looper.java:136)	
at android.app.ActivityThread.main(ActivityThread.java:5017)	
at java.lang.reflect.Method.invokeNative(Native Method)	
at java.lang.reflect.Method.invoke(Method.java:515)	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)	
at dalvik.system.NativeStart.main(Native Method)Caused by: java.lang.IllegalAccessException: access to class not allowed	
at java.lang.Class.newInstanceImpl(Native Method)	
at java.lang.Class.newInstance(Class.java:1208)	
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2395)	
... 10 more
java.lang.IllegalAccessException: access to class not allowed	
at java.lang.Class.newInstanceImpl(Native Method)	
at java.lang.Class.newInstance(Class.java:1208)	
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2395)	
at android.app.ActivityThread.access$1700(ActivityThread.java:135)	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)	
at android.os.Handler.dispatchMessage(Handler.java:102)	
at android.os.Looper.loop(Looper.java:136)	
at android.app.ActivityThread.main(ActivityThread.java:5017)	
at java.lang.reflect.Method.invokeNative(Native Method)	
at java.lang.reflect.Method.invoke(Method.java:515)	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)	at dalvik.system.NativeStart.main(Native Method)

**Comment by litrik** [comment]
I was able to work around this issue by adding the following to AndroidManifest.xml

`
<receiver
            android:name="com.medavox.library.mutime.Persistence"
            tools:node="remove" />
`

If you do not use/need the RECEIVE_BOOT_COMPLETED permission you can also add

`
<uses-permission
        android:name="android.permission.RECEIVE_BOOT_COMPLETED"
        tools:node="remove" />
`
